#!/usr/bin/env bash

scriptdir=`dirname $0`

conf_file=$scriptdir/target-sys.conf

vars="`set -o posix ; set`"; source $conf_file; other_vars="`grep -vFe "$vars" <<<"$(set -o posix ; set)" | grep -v ^vars=`"; unset vars;
other_vars=`echo $other_vars | sed 's/working_dir=[a-zA-Z0-9\/\-]*//'`
other_vars=`echo $other_vars | sed 's/ipc_dir=[a-zA-Z0-9\/\-]*//'`
other_vars=`echo $other_vars | sed 's/num_node=[0-9]*//'`

# prepare zookeeper files
rm -r $working_dir/* 2> /dev/null
mkdir -p $working_dir
cp $scriptdir/startNode.sh $working_dir/startNode.sh
chmod 755 $working_dir/startNode.sh
cp $scriptdir/killNode.sh $working_dir/killNode.sh
chmod 755 $working_dir/killNode.sh
cp $scriptdir/reconfig1.sh $working_dir/reconfig1.sh
chmod 755 $working_dir/reconfig1.sh
cp $scriptdir/reconfig2.sh $working_dir/reconfig2.sh
chmod 755 $working_dir/reconfig2.sh
sed "s:WORKING_DIR:$working_dir:" $scriptdir/zkRunner.sh > $working_dir/zkRunner.sh
chmod 755 $working_dir/zkRunner.sh
cp $scriptdir/readconfig $working_dir/readconfig
cp $scriptdir/dmck.conf $working_dir/dmck.conf
cp $scriptdir/target-sys.conf $working_dir/target-sys.conf
cp $scriptdir/resettest $working_dir/resettest
echo traversal_record_dir=$working_dir/state >> $working_dir/target-sys.conf
echo test_record_dir=$working_dir/record >> $working_dir/target-sys.conf

# prepare log directories & config file
mkdir $working_dir/record
mkdir $working_dir/state
mkdir $working_dir/console
mkdir $working_dir/config
mkdir $working_dir/log


cp $scriptdir/mc_log.properties $working_dir/mc_log.properties
cp $scriptdir/zk_log.properties $working_dir/zk_log.properties

i=0
while [ $i -lt $num_node ]; do
  mkdir -p $working_dir/log/zk$i
	mkdir -p $working_dir/config/zk$i/data
	echo $i > $working_dir/config/zk$i/data/myid
	clientPort=`expr 2180 + $i`
	sed "s:\$nodeId:$i:g" $scriptdir/config/zoo.cfg | sed "s:\$clientPort:$clientPort:g" > $working_dir/config/zk$i/zoo.cfg
	i=`expr $i + 1`
done


#i=0
#while [ $i -lt $num_node ]; do
#	j=0
#	while [ $j -lt $num_node ]; do
#		port1=`expr 8880 + $j`
#		port2=`expr 7770 + $j`
#		echo "server.$j=127.0.0.1:$port1:$port2" >> $working_dir/config/zk$i/zoo.cfg
#		j=`expr $j + 1`
#	done
#	i=`expr $i + 1`
#done

echo "DMCK is ready in $working_dir"

# prepare ipc folders
rm -r $ipc_dir/* 2> /dev/null
mkdir -p $ipc_dir
mkdir $ipc_dir/new
mkdir $ipc_dir/send
mkdir $ipc_dir/ack
echo "IPC-File dirs for DMCK are ready in $ipc_dir"
